# Generated by Django 4.2.19 on 2025-02-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="/users/users_default.png",
                null=True,
                upload_to="users/",
                verbose_name="Аватар",
            ),
        ),
    ]
