# Generated by Django 5.1.4 on 2024-12-24 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Наименование категории")),
                ("description", models.TextField(verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Категория товара",
                "verbose_name_plural": "Категории товаров",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("product", models.CharField(max_length=150, verbose_name="Наименование товара")),
                ("description", models.TextField(verbose_name="Описание")),
                ("image", models.ImageField(upload_to="", verbose_name="Изображение")),
                ("price", models.FloatField(default=1.0, verbose_name="Цена товара")),
                ("created_at", models.DateField(verbose_name="Дата производства")),
                ("changed_at", models.DateField(verbose_name="Дата последнего изменения")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="goods", to="catalog.category"
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "ordering": ["product", "price"],
            },
        ),
    ]
