# Generated by Django 4.2.19 on 2025-02-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="publicated",
            field=models.BooleanField(default=False, verbose_name="Признак публикации"),
        ),
    ]
