# Generated by Django 4.2.19 on 2025-02-10 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_product_publicated"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={
                "ordering": ["first_name", "last_name"],
                "permissions": [("can_unpublish_product", "Can unpublish product")],
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
            },
        ),
    ]
